"""Plugin install / auth smoke test (v1.4.4 reliability release).

The Claude Code plugin install path reads the repo's `.mcp.json` directly.
`install.sh` / `install.ps1` generate a `TD_MCP_SHARED_SECRET` when run, but
the plugin path does not invoke them. Before v1.4.3 that misconfiguration
silently booted the server with auth required + no secret, and every
authenticated request returned 401.

The Fix #1 gate (`server.verify_auth_config`) catches this now. This suite
asserts:

1. The shipped `.mcp.json` *still* declares `TD_MCP_REQUIRE_AUTH=1`
   (if someone removes that, the shipped default changes silently).
2. With just `.mcp.json`'s env and no external secret, `verify_auth_config`
   raises and `tdpilot doctor --skip-td-check` exits non-zero. Proving
   that the plugin install path is loud about its misconfiguration.
3. With `.mcp.json`'s env plus an externally-provided
   `TD_MCP_SHARED_SECRET`, `verify_auth_config` accepts and doctor's
   auth_config line is PASS.

Together these pin the whole "plugin install → auth behaviour" loop
against future drift.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

import td_mcp.server as server


REPO = Path(__file__).resolve().parent.parent
MCP_JSON = REPO / ".mcp.json"


def _shipped_mcp_env() -> dict:
    """Return the env block from the shipped .mcp.json."""
    data = json.loads(MCP_JSON.read_text(encoding="utf-8"))
    servers = data.get("mcpServers", {})
    td = next(iter(servers.values()))  # whichever key — there's only one
    return dict(td.get("env", {}))


def test_shipped_mcp_json_still_declares_require_auth():
    """If this test fails: someone changed the default auth posture in
    the plugin's shipping config. Review the change deliberately."""
    env = _shipped_mcp_env()
    assert env.get("TD_MCP_REQUIRE_AUTH") == "1", (
        f".mcp.json TD_MCP_REQUIRE_AUTH is {env.get('TD_MCP_REQUIRE_AUTH')!r}; "
        "expected '1' (the shipped default). If this is intentional, "
        "update docs/INSTALL_CLAUDE_PLUGIN.md and this test together."
    )
    # The shipped config must NOT embed a literal secret — secrets are
    # per-install, generated by install.sh/install.ps1.
    assert "TD_MCP_SHARED_SECRET" not in env, (
        "shipped .mcp.json must not embed a literal TD_MCP_SHARED_SECRET; "
        "the installer generates it per machine."
    )


def _apply_env(monkeypatch, env: dict, *, secret: str | None = None) -> None:
    """Apply shipped .mcp.json env to the test process, optionally adding a secret."""
    for key, value in env.items():
        monkeypatch.setenv(key, str(value))
    if secret is not None:
        monkeypatch.setenv("TD_MCP_SHARED_SECRET", secret)
    else:
        monkeypatch.delenv("TD_MCP_SHARED_SECRET", raising=False)


def test_plugin_install_unconfigured_trips_auth_gate(monkeypatch):
    """Shipped .mcp.json + no external secret → `verify_auth_config` raises.

    This is the regression the v1.4.3 auth fix prevents. If this test
    passes without the fix, we've regressed.
    """
    env = _shipped_mcp_env()
    _apply_env(monkeypatch, env, secret=None)

    with pytest.raises(RuntimeError) as exc:
        server.verify_auth_config()
    assert "TD_MCP_SHARED_SECRET" in str(exc.value)
    assert "install" in str(exc.value).lower()


def test_plugin_install_unconfigured_doctor_fails(monkeypatch, capsys):
    """Shipped .mcp.json + no external secret → doctor exits non-zero
    and the auth_config line is marked FAIL."""
    env = _shipped_mcp_env()
    _apply_env(monkeypatch, env, secret=None)

    with pytest.raises(SystemExit) as exc:
        server.main(["doctor", "--skip-td-check"])
    assert exc.value.code != 0

    out = capsys.readouterr().out
    auth_line = next(
        (line for line in out.splitlines() if "auth_config" in line), ""
    )
    assert "FAIL" in auth_line


def test_plugin_install_with_secret_passes_gate(monkeypatch):
    """Shipped .mcp.json + external secret → verify_auth_config accepts."""
    env = _shipped_mcp_env()
    _apply_env(monkeypatch, env, secret="plugin-install-secret-" + "x" * 32)
    server.verify_auth_config()  # must not raise


def test_plugin_install_with_secret_doctor_auth_passes(monkeypatch, capsys):
    """Shipped .mcp.json + external secret → doctor's auth_config line is PASS."""
    env = _shipped_mcp_env()
    _apply_env(monkeypatch, env, secret="plugin-install-secret-" + "x" * 32)

    with pytest.raises(SystemExit):
        server.main(["doctor", "--skip-td-check"])

    out = capsys.readouterr().out
    auth_line = next(
        (line for line in out.splitlines() if "auth_config" in line), ""
    )
    assert "PASS" in auth_line
    assert "FAIL" not in auth_line


def test_plugin_install_disabled_auth_passes(monkeypatch):
    """Alternative install mode: auth explicitly disabled.

    If a user manually sets TD_MCP_REQUIRE_AUTH=0 (not recommended but
    allowed), the gate should not trip — there's nothing to enforce.
    """
    env = _shipped_mcp_env()
    env["TD_MCP_REQUIRE_AUTH"] = "0"
    _apply_env(monkeypatch, env, secret=None)
    server.verify_auth_config()  # must not raise
