"""Snapshot test for every MCP tool's input schema + metadata.

Catches silent backward-incompat changes: a renamed parameter, a required
field becoming optional (or vice versa), or a tool name removed. The schema
file lives at ``tests/fixtures/tool_schemas.json`` and is regenerated by
running this file with ``TDPILOT_UPDATE_SCHEMA=1``.

Pattern borrowed from snapshot-testing in frontend: fast to run, the diff
is reviewable in PR, and it blocks drift without requiring hand-rolled
per-tool assertions. Complements the existing name-set contract test.
"""

from __future__ import annotations

import asyncio
import json
import os
from pathlib import Path
from typing import Any

import td_mcp.server as server

SNAPSHOT_PATH = Path(__file__).parent / "fixtures" / "tool_schemas.json"


def _collect_snapshot() -> dict[str, Any]:
    tools = asyncio.run(server.mcp.list_tools())
    snapshot: dict[str, Any] = {}
    for tool in tools:
        # Normalize — pydantic schemas have title/description that vary with
        # docstring tweaks; keep the structural shape (params, required, types).
        schema = tool.inputSchema or {}
        properties = schema.get("properties", {})
        required = sorted(schema.get("required", []))
        snapshot[tool.name] = {
            "description_present": bool(tool.description),
            "required": required,
            "properties": {
                name: {
                    "type": prop.get("type"),
                    # 'anyOf' encodes X | None; we keep only the key names.
                    "any_of_types": sorted(
                        [m.get("type") for m in prop.get("anyOf", []) if m.get("type")]
                    ),
                    "enum": prop.get("enum"),
                    "default_present": "default" in prop,
                }
                for name, prop in properties.items()
            },
        }
    return dict(sorted(snapshot.items()))


def _load_snapshot() -> dict[str, Any]:
    if not SNAPSHOT_PATH.exists():
        return {}
    return json.loads(SNAPSHOT_PATH.read_text())


def _write_snapshot(data: dict[str, Any]) -> None:
    SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT_PATH.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def test_tool_schemas_match_snapshot():
    """Regenerate with: TDPILOT_UPDATE_SCHEMA=1 uv run pytest tests/test_tools_schema_snapshot.py"""
    current = _collect_snapshot()

    if os.environ.get("TDPILOT_UPDATE_SCHEMA") == "1":
        _write_snapshot(current)
        return  # skip diff on regen

    stored = _load_snapshot()
    if not stored:
        # First run — establish the baseline rather than fail.
        _write_snapshot(current)
        return

    # Build a small diff report if they disagree.
    added = sorted(set(current) - set(stored))
    removed = sorted(set(stored) - set(current))
    changed = sorted(
        name
        for name in set(current) & set(stored)
        if current[name] != stored[name]
    )

    if added or removed or changed:
        details = []
        if removed:
            details.append(f"REMOVED tools: {removed}")
        if added:
            details.append(f"ADDED tools: {added}")
        if changed:
            details.append(f"CHANGED tools (schema drift): {changed[:10]}")
        details.append(
            "If this is an intentional change, regenerate the snapshot with:\n"
            "  TDPILOT_UPDATE_SCHEMA=1 uv run pytest tests/test_tools_schema_snapshot.py -q"
        )
        raise AssertionError("Tool schema drift:\n" + "\n".join(details))
